service-mesh-performance/service-mesh-performance

- README.md
fixes #4 
Signed-off-by: ashiscs <ashissingh640@gmail.com>
> updated other meshery resources section

- smps.yaml
Signed-off-by: Naveen Jain <nveenjain@gmail.com>
> Added endpoint URL to the spec

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/documentation.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
> added issue templates

- smps.proto
I have segregated the SMPS object into different objects in the protofile.
> Segregate SMPS proto into seperate objects

- Makefile
- go.mod
I have made some fixes because I had issues importing this in meshery.
> Fix imports

- README.md
Signed-off-by: leecalcote <leecalcote@gmail.com>
Adding workload configuration as it own call out.
> readme: workload configuration

- docs/_config.yml
- docs/_data/navigation.yml
- docs/_data/sitetext.yml
- docs/_includes/navheader.html
- docs/_includes/subscribe.html
- docs/_sass/components/_navbar.scss
- docs/_sass/layout/_masthead.scss
- docs/_sass/layout/_subscribe.scss
This PR fixes:
- Navigation issues
- Header and Footer styling
> [SMPS site]: Update

- docs/_config.yml
> Google analytics tracking id

- CONTRIBUTING-gitflow.md
- CONTRIBUTING.md
- docs/README.md
Signed-off-by: PluckyPrecious <prekel27@gmail.com>
Created Doc README.md, CONTRIBUTING-gitflow.md file and some edits in the CONTRIBUTING.md
This PR fixes #68
@leecalcote please check this out.
> Added smps-spec contributing doc

- .github/workflows/release-drafter.yml
Signed-off-by: Jubayer Abdullah Joy <jubayerjoycse@gmail.com>
Leverage (copy) the releasedrafter configuration from the meshery repo.
- https://github.com/layer5io/meshery/blob/master/.github/workflows/release-drafter.yml
This PR fixes #76 
> Add releasedrafter

- CONTRIBUTING-gitflow.md
- CONTRIBUTING.md
- README.md
This will fix broken links from #84 in the README and should facilitate and solve any merge conflicts for #81.
> [Update] Convert all references of smps --> smp 

- .github/ISSUE_TEMPLATE/documentation.md
Signed-off-by: PluckyPrecious <prekel27@gmail.com>
This is an update for SMP contribution issue templates.
This PR fixes #75
This - [Service Mesh Performance documentation site](https://smp-spec.io/docs) will be active upon completion of #90
> Update Issue Template to SMP

- docs/_includes/implementation.html
- docs/_layouts/default.html
- docs/_sass/components/_navbar.scss
- docs/_sass/layout/_implementation.scss
- docs/_sass/layout/_masthead.scss
Signed-off-by: Nikhil-Ladha <nikhilladha1999@gmail.com>
This PR fixes #93 , #94 
And also, updated the style in the header background image and few responsive tweaks.
> [UI]:Few style tweaks and updated the github stats

- .github/workflows/slack.yml
- docs/Makefile
- docs/_sass/base/_page.scss
- docs/_sass/base/_variables.scss
> Good riddance S

- .github/config.yml
Signed-off-by: Akash Gupta <akashgp9@gmail.com>
Added Reminder in the Welcome Bot to star SMP Project
This PR fixes #107
-  Yes, I signed my commits.
> Added Reminder: Please Star the project

- CONTRIBUTING.md
Signed-off-by: Oyinkansolami Atansuyi <tomisinatansuyi@gmail.com>
This PR fixes #102 
> added RVM Description to SMP Documentation

- CONTRIBUTING.md
Signed-off-by: PluckyPrecious <prekel27@gmail.com>
Added Jekyll cavaet and some fixes.
This PR fixes #117 
> [Doc] Update contributing doc with cavaet 

- docs/_includes/head.html
Signed-off-by: Partha Paul<parthapaul47@gmail.com>
This PR fixes #126 
1. Simply removed Specification from head.html which was dropped for a long time
- [ *] Yes, I signed my commits.
> #126 - Dropped Specification from head section w/signoff

- docs/_includes/about.html
- docs/_includes/hero.html
- docs/_includes/nav.html
- docs/_sass/components/_buttons.scss
- docs/_sass/components/_navbar.scss
- docs/_sass/layout/_about.scss
- docs/assets/css/agency.scss
- docs/assets/js/nav-shrink.js
This PR updates the following things :-
- Enlarged SMP brand logo on navbar
- Added shrink on scroll to SMP brand logo
- Reduced "SMP IN-ACTION" button drop-shadow.
- Added responsive centering of "Standardizing Service Mesh Value Measurement" and "SMP IN-ACTION" button across all devices.
**Demo**
• Before :
• After :
Refer to [this](https://docs.google.com/document/d/1EnFMGyPbsQ3h-YuYE0Jutew79NrPzPNTVxLu8rvqRzE/edit)!
Will soon be updating the **contributors section**! :smile: 
> Updated SMP page

- docs/_data/sitetext.yml
Signed-off-by: Gerald Maboshe <maboshegerald1@gmail.com>
Google's logo has been removed from smp-spec.io site
This PR fixes #129 
N/A
> Removed Google Logo from smp-spec.io

- docs/Gemfile.lock
- docs/_includes/contributors.html
- docs/_sass/layout/_contributors.scss
Adjusted contributor logos display by adding a horizontal scrollbar to the contributors section
This PR fixes #111 
@chandrashritii  @leecalcote
> Added a horizontal scrollbar to the contributors section

- docs/_data/sitetext.yml
- docs/_includes/engage.html
- docs/_sass/layout/_engage.scss
Renovated the Resources section of the [SMP site](https://smp-spec.io/). Upgrade visible across all devices!
This PR fixes #136 
> [Site] Enhanced Resources section

- docs/_includes/footer.html
- docs/_sass/layout/_footer.scss
- docs/assets/css/responsive.css
- Optimized the footer section for mobile view.
This PR fixes #141 
> Optimized the footer section for mobile view

- protos/service_mesh.proto
Signed-off-by: cld <lumenluwiz@gmail.com>
Added NGINX service mesh to the proto file.  
This PR fixes #143 
> Added NGINX service mesh

- docs/_includes/about.html
- docs/_sass/layout/_about.scss
Signed-off-by: Aayush <aayush.bcode@gmail.com>
This PR fixes #146
> KubeCon video and slides added

- docs/_layouts/page.html
Signed-off-by: Navendu Pottekkat <navendupottekkat@gmail.com>
Wraps a card element around the blog posts for a better look.
This PR fixes #138
> wrap card to blog post

- docs/_layouts/default.html
Signed-off-by: jomefavourite <jfjomefavourite@gmail.com>
Added a function to insert a comma
This PR fixes #153
> added a function for comma insertion

- protos/service_mesh.proto
- spec/service_mesh.pb.go
Signed-off-by: Prayag Jain <offpjain@gmail.com>
This PR fixes #159 
> Name change from Maesh to Traefik Mesh

- .github/ISSUE_TEMPLATE/site_update.md
Signed-off-by: Shimon Wosner <shwosner@gmail.com>
This PR fixes #163 
> added site_update.md

- .gitignore
This PR fixes #167 
Preview gif as it may not be shown in github review:
Kindly check the above gif, I tried to keep the recording as short as possible. Please let me know if something needs to be chopped out of the gif or if something needs to be included.
> Replace SMP example gif

- README.md
Signed-off-by: Gaurav Chadha <gauravchadha1676@gmail.com>
Updated "Access Community Drive" to "To Access Community Drive, fill Community Member Form" in the community section.
This PR fixes #186 
> Replace community drive with community form

- README.md
The README.md had some failing badges & wrong alignment.
**What did I changed:**
- Fixed Badges
- Aligned the Badges to center
**Screenshot of new changes:**
This PR fixes #192 
None
> Fix badges & alignment in README.md

- MAINTAINERS.md
This PR published SMP's set of maintainers.
> [Chore] Update Maintainers List

- README.md
Signed-off-by: Parth <img_2019045@iiitm.ac.in>
This PR fixes #197 
> Added community forum to readme w/signoff

- docs/_includes/about.html
Signed-off-by: Ayushman Mishra <ayushvidushi01@gmail.com>
This PR fixes #194 
> added google-slides

- LICENSE
- docs/LICENSE
- docs/_includes/footer.html
- docs/assets/js/back-to-top-smp.js
Signed-off-by: Navendu Pottekkat <navendupottekkat@gmail.com>
This PR fixes #199 
This PR changes all the occurrences of "© 2021 Layer5, Inc." to "© 2021 The SMP Authors".
These include the footer in the website and the Licenses.
> Update copyright info to "The SMP Authors"

- .github/workflows/slack.yml
Signed-off-by: aisuko <urakiny@gmail.com>
This PR fixes #206 
> Upgrade the Github Aaction to use environment

- .github/workflows/slack.yml
- docs/_includes/about.html
- docs/_includes/cncf-project.html
- docs/_sass/base/_page.scss
- docs/_sass/components/_navbar.scss
- docs/_sass/layout/_footer.scss
- docs/assets/css/responsive.css
Signed-off-by: Aditya Chaterjee <speak2adi@gmail.com>
fixed mobile responsive issues of nav-bar, google slides and code snippet.
This PR fixes #213 
> Added mobile responsiveness to the whole page

- README.md
_Signed-off-by: amino19 <anshumaankrprasad76@gmail.com>_
CII best practices badge updated..
This PR fixes #NA
Ready to merge!
Preview :-
> [README] CII best practices badge updated

- docs/_data/sitetext.yml
- docs/_includes/engage.html
Signed-off-by: Navendu Pottekkat <navendupottekkat@gmail.com>
This PR adds the SMP community meeting details to the website.
> add SMP community meeting details

- docs/_includes/engage.html
This PR fixes #221
The SMP community grp reference centered and meeting minutes icon improved
@navendu-pottekkat  and @leecalcote  Please do have a look!
> Reference to SMP community group improved

- CONTRIBUTING.md
Signed-off-by: Saptarshi Patra
Contributing instructions updated
This PR fixes #229 
> Contributing instructions updated

- docs/_includes/subscribe.html
- docs/_sass/base/_page.scss
- docs/_sass/layout/_subscribe.scss
Signed-off-by: Nikhil Sharma <nikhilsharmamusic2000@gmail.com>
- Added Mailing List to the SMP site
- Maintained the responsiveness for small screens
This PR fixes #205
- Please check if the links are correct
- Let me know if there are any other changes we can make
> [Site] Added Mailing List

- CONTRIBUTING.md
Signed-off-by: Zain-Muiz <zainu10863@gmail.com>
Pointed towards Meshery Docs in case of errors during installation or setup.
Points to the part of the docs that is to fix issues in the dev environment.
> Pointed towards Meshery Docs in case of errors during installation

- .github/workflows/slack.yml
Please review it once
This PR #246 fixes the [slack.yml] workflow file.
> Fixing slack notify on star

- docs/Gemfile.lock
- docs/_sass/layout/_footer.scss
Signed-off-by: Ghulam Yazdani <ghulamyazdani12@gmail.com>
Fixed the misalignment of the header in mobile view.
This PR fixes #261
Ready for the review!
> [UI] misalignment of header in mobile view fixed

- docs/_sass/layout/_cncf-project.scss
- docs/_sass/layout/_footer.scss
Signed-off-by: akshatnema <20bcs022@iiitdmj.ac.in>**Description**
This PR fixes #263.
> corrected alignment of objects

- README.md
- docs/_data/sitetext.yml
- docs/_includes/engage.html
Signed-off-by: Vedant Kakde <69970950+vedant-kakde@users.noreply.github.com>
This PR fixes #266 
> Updated YouTube channel hyperlinks

- .github/ISSUE_TEMPLATE/site_update.md
Signed-off-by: esteebrooks <esteebrooks@gmail.com>
This PR fixes #267 
First open source commit!
- [x ] Yes, I signed my commits.
> Enhanced Contributor Guides 

- docs/_includes/head.html
Signed-off-by: toth2000 <tothagata.bhattacharjee@gmail.com>
Add schema for better SEO
This PR fixes #259 
> Add schema for better SEO

- GOVERNANCE.md
Signed-off-by: Aditya Chaterjee <speak2adi@gmail.com>
Added the Governance.md file
> adde governance.md

- docs/_layouts/page.html
Signed-off-by: toth2000 <tothagata.bhattacharjee@gmail.com>
Update: if condition for rendering `by {{page.author}}` span.
This PR fixes #275 
> Fix: Unwanted 'by' text in '/blog'

- docs/_sass/base/_page.scss
Signed-off-by: Ghulam Yazdani <ghulamyazdani12@gmail.com>
Fixed the misalignment of content in the website in mobile view
This PR fixes #264
Ready for review!
> [UI] Fixed the alignment of contents in website 

- CONTRIBUTING-gitflow.md
- CONTRIBUTING.md
Signed-off-by: Mr-DG-Wick <deepakgdkg1g8868@gmail.com>
fixed some minor typos
> [Doc] minor-typo fixes

- docs/_sass/layout/_subscribe.scss
- docs/assets/css/responsive.css
Signed-off-by: Sahil Suman <sahilsuman933@gmail.com>
1.Fixed Button Overlay Issue by adding margin-right: -2px;
2.Fixed a Typo in Responsive CSS File
This PR fixes #277
> Responsive Overlapping Buttons Fix

- docs/Gemfile
- docs/Gemfile.lock
Signed-off-by: Lakshya Singh <lakshay.singh1108@gmail.com>
Add in `webrick` to support ruby 3.0.0 builds based on highly accepted and tested answer for issue:
- https://github.com/jekyll/jekyll/issues/8523#issuecomment-751409319
This PR fixes #279
> Ruby 3.0.0 Support

- .github/workflows/newcomer-alert.yml
- .github/workflows/slack.yml
Signed-off-by: Jerod Culpepper cpepper96@gmail.com
This PR fixes #289 
> Update slack.yml/added newcomers-alert

- protos/service_mesh.proto
Signed-off-by: Suryashankar Das <suryashankardas.2002@gmail.com>
This PR fixes #294
> Add support for Cilium Service Mesh

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
- .github/ISSUE_TEMPLATE/site_update.md
This PR fixes #293
Updated the issue templates in a format similar to meshery and meshery.io's
> Issue templates updated

- docs/_includes/subscribe.html
Signed-off-by: Vidyaa <mailvidyaa@gmail.com>
This PR fixes # 298
Used required attribute in the input fields of Newsletter form to not proceed without all the required inputs and removed "novalidate" from the form to allow validation.
> added required field and removed novalidate from form

- README.md
Signed-off-by: Gaurav Chadha <gauravchadha1676@gmail.com>
Handbook info addition 
This PR fixes #CU-1ydvcdq
> [Docs] Handbook info addition | CU-1ydvcdq

- docs/_includes/nav.html
- docs/_layouts/dashboardPage.html
- docs/_sass/components/_navbar.scss
- docs/_sass/layout/_dashboard.scss
- docs/assets/js/toggle.js
> [SITE] [DASHBOARD]added solid border around dashboard on navigation

- docs/_layouts/dashboardPage.html
- docs/_sass/layout/_dashboard.scss
Signed-off-by: Debopriya Bhattacharjee <debopriyabhattacharjee@Debopriyas-MacBook-Air.local>
This PR fixes #311 
> Fix for dashboard sidebar overlapping with footer

- docs/_data/service_meshes.yml
- docs/_includes/javascript_files.html
- docs/_layouts/dashboardPage.html
- docs/_sass/layout/_dashboard.scss
- docs/assets/js/toggle.js
- docs/pages/dashboard/burst_test.md
- docs/pages/dashboard/jwt_revocation_test.md
- docs/pages/dashboard/soak_test.md
This PR Updates Following things:
1. Implemented a more easy way to add service meshes
2. Made the site responsive, (mainly the vertical navbar and the content of the page)
3. Each performance profile have page of their own
4. Reverted some of the changes made in #313 (figured out the j query was needed)
This PR updates #272
> [Dashboard] Some changes

- docs/_includes/graph.html
- docs/_layouts/dashboardPage.html
- docs/assets/js/billboard.js
- docs/assets/js/toggle.js
This PR updates #272
1. refactoring left
2. just the chart is functional the selector is not.
> [Dashboard] Added graph for a hardcoded performance result

- docs/_includes/graph.html
- docs/_sass/layout/_dashboard.scss
- docs/assets/js/billboard.js
> [Dashboard] added graph details

- README.md
> Update SMP Community Meetings info in README.md

- docs/_data/test-results.json
- docs/_layouts/dashboardPage.html
- docs/_sass/layout/_dashboard.scss
- docs/assets/js/billboard.js
- docs/assets/js/toggle.js
> Updates on dashboard

- docs/_data/navigation.yml
- docs/_includes/nav.html
- [ x] Yes, I signed my commits.
> added meshmark on navigation

- docs/_sass/layout/_meshmark.scss
> made the meshmark page responsive

- docs/_layouts/defaultPage.html
Signed-off-by: Yash Kamboj <yashkamboj29@gmail.com>
Added shrink functionality to meshmark page
This PR fixes #340 
> [Bug] Added shrink functionality to meshmark page

- docs/_includes/sidebar.html
> fixed trailing slash error on links

- docs/assets/js/profiles.js
Now the cards for the performance profile which do not have any results are not shown on the webpage.
> removed performance profile that doesn't have results

- docs/assets/js/profiles.js
Signed-off-by: Yash Kamboj <yashkamboj29@gmail.com>
404 issue solved, issue was due to a "/" , the pagination url was different from the page url
This PR fixes #348 
> Solved 404 error by pagination

- docs/assets/js/profiles.js
- docs/assets/js/table.js
The earlier changes #349 seems to have broken the site, now the dashboard page does not opens at all. This page reverts that changes and makes a Possible fix for the 404 error on page change on the results table.
> [Dashboard] reverted changes, possible fix for 404

- docs/_layouts/performanceProfileTable.html
- docs/_sass/layout/_dashboard.scss
- docs/assets/js/profiles.js
- docs/assets/js/renderChart.js
- docs/assets/js/table.js
The following PR will address the following changes:
1. Remove the Load time when going to new page on the table view
2. Show all the missing value of the test Specifications
3. Change the color of the headers on the individual results page
4. Changed profiles card formatting 
5. Change the title of the individual results from `2022-08-15-22.15.08` to `15th August 2022, 22:15:08 UTC` [WIP] [Suggestion Needed]
> [Dashboard] Updates on the Dashboard

- docs/_includes/footer.html
- docs/_sass/layout/_footer.scss
Signed-off-by: Neeraj Anand <neeraj.2@iitj.ac.in>
This PR fixes #336. 
- Added some bootstrap inline styling for fixing the responsiveness of footer component
**Demo After Changes**
https://user-images.githubusercontent.com/56186425/186788761-f1993f42-6a0e-4f1a-88f5-f38a3bb73e64.mov
> Fixed responsiveness for footer component

- docs/pages/dashboard/methodology/methodology.md
Signed-off-by: Huang Xin <xin1.huang@intel.com>
> Fix typos in docs/pages/dashboard/methodology.md.

- docs/_sass/layout/_about.scss
This PR fixes #363 Alignment fixed 
> Presentation video alignment fix

- docs/_includes/sidebar.html
- docs/_sass/layout/_footer.scss
Signed-off-by: Aditya <adityasinghboss1234@gmail.com>
This PR adds the methodology page link in the sidebar of dashboard page
This PR fixes #367 
> Added methodology page link on dashboard

- docs/_layouts/default.html
- docs/assets/js/profiles.js
- docs/assets/js/renderChart.js
- docs/assets/js/table.js
> [chore ] Update remote provider APIs

- docs/pages/dashboard/index.md
> Trying fixing  trailing slash error

- docs/pages/dashboard/load_test.md
- docs/pages/dashboard/soak_test.md
> Trailing Slash Fix on soak and load pages

- docs/pages/dashboard/load_test.md
- docs/pages/dashboard/soak_test.md
Reverts service-mesh-performance/service-mesh-performance#377
This change did work quite well. @asubedy 
https://user-images.githubusercontent.com/73700530/232483149-d8ad2102-ae18-408b-ad6a-83150643e566.mov
> Revert "Trailing Slash Fix on soak and load pages"

- README.md
This PR fixes the link redirecting to newcomers guide
> newcomers guide provided

- docs/assets/js/profiles.js
> Fixed information shown on SMP dashboard

- docs/_config.yml
- docs/_includes/analytics_body.html
- docs/_includes/analytics_head.html
- docs/_includes/head.html
- docs/_layouts/dashboardPage.html
- docs/_layouts/default.html
- docs/_layouts/defaultPage.html
- docs/_layouts/individualResults.html
- docs/_layouts/page.html
- docs/_layouts/performanceProfile.html
- docs/_layouts/performanceProfileTable.html
- docs/_layouts/post.html
> migrate smp to google tag mamager

- docs/_sass/layout/_dashboard.scss
- docs/collections/_posts/2022-01-26-pipelining-service-mesh-specifications.md
- Resolved the yaml code syntax error by removing the extra space and maintaining the correct yaml lint validated code.
- Added the spaces to resolve the error "+" and "-" must be surrounded by whitespace in calculations while using make site command.
This PR fixes #409 
> Resolved the YAML code syntax

- docs/_includes/related-discussion.html
Signed-off-by: Hemant M Mehta [hemant29mehta@gmail.com](mailto:hemant29mehta@gmail.com)
This PR fixes #400
I have updated the Discussion Forum Link
> Updated Forum Link

- docs/collections/_posts/2020-05-21-meshmark-explained.md
This PR The updates https://layer5.io/projects/service-mesh-distributed-performance-management with : https://layer5.io/projects/nighthawk
> update broken link

- docs/_layouts/performanceProfileTable.html
This PR fixes #401 
This PR makes the results table horizontally scrollable so the user can see the other two columns.
> Made result table responsive

- docs/_includes/meshmark.html
This PR fixes #419 
The join us was already redirecting to layer5 blogs so it should reflect as Read
> Change format of event post

- docs/_includes/nav.html
- docs/_sass/base/_page.scss
- docs/_sass/components/_navbar.scss
- docs/_sass/layout/_masthead.scss
- docs/assets/css/responsive.css
Updates togglebar, menu design and resolved some responsiveness issues
[smp.webm](https://github.com/service-mesh-performance/service-mesh-performance/assets/54661456/b8b17ba8-9fcb-4384-99f0-eec054d9873c)
This PR fixes # 427
> [Fix] Togglebar, Menu, and responsiveness updates

- docs/_data/sitetext.yml
> change twitter logo to x logo

- docs/_includes/posts_grid.html
This PR fixes #428
[DEMO.webm](https://github.com/user-attachments/assets/8c2d0eee-bc43-42ae-85ff-92d6d0e7c5d4)
> card issue resolved

- .github/workflows/ci.yml
> ci(lint): Fix golint error

- docs/Makefile
- docs/_layouts/default.html
- docs/assets/js/profiles.js
- docs/assets/js/renderChart.js
- docs/assets/js/table.js
> update cloud endpoints hostname
